### ISSUE TITLE
How to append new permissions to existing roles?

### ISSUE THREAD

**Issue by vijayshreem-cuelogic** [rails-engine/role_core#3]
I have a Users , Role Assignments and Roles table. I had created roles 'Admin', 'Integrator' with certain initial permission Create, Edit , Destroy (defined inside config/initializers/role_core.rb). 
1. Now, I want to add a new permissions for a model 'Task'. 
How can I achieve this without affecting (resetting) my existing permissions already saved into database? (on the fly)
How can I re-group a permission or add a group on the fly?
2. I don't have necessarily a "model" Task 
(for eg. group :task_management, model_name: 'Task').
Can I configure grouping without having a model?

Please help. Thanks in advance !

**Comment by jasl** [comment]
1. Appending new permissions doesn't need you do any migration on existence records

You can simply add some new permissions, and examine it in Rails console if you don't have a management UI yet, like `user.roles.first.permissions.a_new_permission?`

2. Of course you can

`model_name` is for CanCanCan integration (it will be translated to CanCanCan definition in runtime), if you need to integrate with CanCanCan but want some permissions or groups don't be translated automatically, just given `_callable: false` (e.g: `group :task_management, _callable: false`)

If you're not integrate with CanCanCan, you're no need given `model_name`

**Comment by jasl** [comment]
If you still have trouble according to my explain, that should be my fault.

**Comment by jasl** [comment]
By design, Role only support static permissions (which defined in source code), I think this is the most use case.

But, you still can do much more, if your `dynamic permissions` means permissions are persisted in database, for example:

- Design a model to persisting dynamic permissions, e.g `DynamicPermission(id: bigint, name: string, default: bool)`
- Add `dynamic_permissions` column (`text` type) to Role model to persisting dynamic permissions' configuration, and in your model `serialize :dynamic_permissions, Hash`
- Generate dynamic permissions set in runtime
  ```ruby
  # Create a new permission set to containerize dynamic permissions
  dynamic_permission_set_class = PermissionSet.derive "Dynamic" # "Dynamic" can be named to other but must be a valid Ruby class name, that's a hacking for ActiveModel::Naming

  # Fetching dynamic permissions
  dynamic_permissions = DynamicPermission.all

  # Mapping dynamic permissions to permission set
  dynamic_permission_set_class.draw do
    dynamic_permissions.each do |p|
      permission p.name, default: p.default
    end
  end
  ```
- Create a instance of this dynamic permission set
  ```ruby
  dynamic_permissions = dynamic_permission_set_class.new(role.dynamic_permissions)
  ```
- You can use the `dynamic_permissions` now as my `Readme` described.

Rails' `serialize` is static so you must do serialize and deserialize manually, you can wrap these logic into model.

PS: I don't know if a model has `serialize :dynamic_permissions, Hash` and you define a `dynamic_permissions` method is safe or not.

**Comment by vijayshreem-cuelogic** [comment]
Thanks. I will try to implement this. 
One last thing. I have cancancan implemented in my project. To understand how ability works I had gone through test/dummy app inside rolecore. I created a role and assign "New project" permission to it. But, can? :create, Project returns false.
Any reason?

**Comment by vijayshreem-cuelogic** [comment]
Thanks @jasl. Its working.

**Comment by johnnoelvictorino** [comment]
May I ask for specific instructions for the dynamic permissions i.e., in which file do I add the code snippets?
